# Generated by Django 5.1.7 on 2025-03-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0002_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
