# Generated by Django 5.1.7 on 2025-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0003_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
