# Generated by Django 5.1.7 on 2025-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0004_userprofile_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='departmentAllocation',
            field=models.CharField(blank=True, choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3'), ('Location 4', 'Location 4')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='departmentName',
            field=models.CharField(blank=True, choices=[('Name 1', 'Name 1'), ('Name 2', 'Name 2'), ('Name 3', 'Name 3'), ('Name 4', 'Name 4')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, null=True),
        ),
    ]
