# Generated by Django 5.1.7 on 2025-03-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0005_alter_userprofile_departmentallocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='departmentAllocation',
            new_name='department_allocation',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='departmentName',
            new_name='department_name',
        ),
    ]
