# Generated by Django 5.1.7 on 2025-04-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0006_rename_departmentallocation_userprofile_department_allocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
