# Generated by Django 5.1.7 on 2025-04-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0008_lockoutlog_is_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockoutlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lockoutlog',
            name='os_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lockoutlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
