# Generated by Django 5.1.7 on 2025-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logIn', '0009_lockoutlog_device_type_lockoutlog_os_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
